### PR TITLE
[skip ci] -Added my instance (https://translate.plausibility.cloud)

### PR DESCRIPTION
**Pull request by m2jest1c**
I just added my instance, nothing crazy. Hoping the additions of the spaces and dashes in the readme.md are fine, I don't really know, so..

### CODE REVIEW

**Comment by m2jest1c** [comment]
wait I just realized I forgot the skip CI damn it

**Comment by m2jest1c** [comment]
Well I doubt editing the title does anything and I can't delete this to hide my stupidity so I'll just reopen it and hope someone can educate me on this 😭

**Comment by TheDavidDelta** [comment]
Thank you for your instance!! And don't worry about that. It's just that the `[skip ci]` thing should be inside the commit message and not the PR title.
The spacing is perfect, thanks! But please also add the instance to [this file](https://github.com/TheDavidDelta/lingva-translate/blob/main/instances.json) (and by the way add `[skip ci]` to that commit :smile:).

**Comment by m2jest1c** [comment]
Wait, didn't I add it in bccf9e3? I did edit the file before pushing and it shows in the commits and files changed tab

**Comment by TheDavidDelta** [comment]
Oh yes, I'm sorry, merging!

**Comment by m2jest1c** [comment]
Thanks friend!

**Pull request merged**
