### PR TITLE
added my instance :)

### PR DESCRIPTION
**Pull request by EsmailELBoBDev2**

### CODE REVIEW

**Comment by TheDavidDelta** [comment]
Amazing! Thank you!
Please, can you also add the instance to the `instances.json` file (without the last slash)? It's a new file we had to create just yesterday in #84.
Also, if you don't bother, please try to keep the Markdown table code fit.
imagen
Thank you again.
Regards, David.

**Comment by EsmailELBoBDev2** [comment]
Oh i was editing inside git so i did not notice those makrdown erros, sorry!

**Comment by EsmailELBoBDev2** [comment]
https://github.com/TheDavidDelta/lingva-translate/pull/87

**Comment by TheDavidDelta** [comment]
Don't worry! Just add the edit together with the instances commit :smile:

**Comment by EsmailELBoBDev2** [comment]
:+1:

**Comment by TheDavidDelta** [comment]
Didn't know I could create commits in other people's PR lmao. Just did it myself hahaha. Thank you for the instance!

**Comment by EsmailELBoBDev2** [comment]
Oh you can :joy: 

For me i did not know i can change files afterwards i create PR so learnt new thing today!

**Pull request merged**
