### PR TITLE
add translate.alefvanoon.xyz

### PR DESCRIPTION
**Pull request by alefvanoon**

### CODE REVIEW

**Comment by TheDavidDelta** [comment]
Amazing! The first non-official instance!
Sorry for being this late, couldn't reply earlier.
Btw the CI is failing because of a environment permissions problem that I'll fix in my next PR so I'll just ignore it and merge.

**Comment by TheDavidDelta** [comment]
Hi,

It seems this instance have been down for a few weeks and someone created a PR for removing it from the Readme (#25), but I'd like to ask you if we should remove it or not as you are the creator.

Regards, David.

**Comment by alefvanoon** [comment]
Hi,
thanks for asking.
It's not down, just have typo. sorry.
Checkout #26

**Comment by TheDavidDelta** [comment]
Perfect, gonna merge!

**Pull request merged**
