### PR TITLE
Remove translate.alefvanoon.xyz as it's down

### PR DESCRIPTION
**Pull request by victorbnl**

### CODE REVIEW

**Comment by TheDavidDelta** [comment]
Thanks for this. I was already planing to remove it because it have been down for 3 weeks or so, but before making any changes I've asked the instance's creator in his own PR (as mentioned) and I'd like to wait for his reply.

**Comment by alefvanoon** [comment]
it's not down.
just have  typo :((((
https://translate.alefvanoon.xyz/

**Comment by alefvanoon** [comment]
#26

**Comment by TheDavidDelta** [comment]
Oh, sorry then, thanks for your fast response, gonna merge.

**Pull request closed without merging**
