### PR TITLE
Add arm64 as a build target for the docker image

### LINKED ISSUE #62: Lingva docker image isn't working on raspberry pi
Lingva docker image isn't working on raspberry pi. Please check the issue.

### PR DESCRIPTION
**Pull request by TheFrenchGhosty**
Fixes #62 

Note: I'm not super experienced with Docker image builds and Docker container creation so it's maybe wrong.

Resource used: https://docs.travis-ci.com/user/multi-cpu-architectures/

### CODE REVIEW

**Comment by TheFrenchGhosty** [comment]
https://github.com/TheDavidDelta/lingva-translate/pull/64/checks?check_run_id=4068246502 > 2 jobs

https://app.travis-ci.com/github/TheDavidDelta/lingva-translate/jobs/546082373 amd64 build

https://app.travis-ci.com/github/TheDavidDelta/lingva-translate/jobs/546082374 arm64 build

**Comment by TheFrenchGhosty** [comment]
Ah... the arm64 build failed because for whatever reason it got a SSL error when installing yarn

**Comment by TheFrenchGhosty** [comment]
Focal arm64 didn't have xvfb installed by default (while it is on amd64), this should now work... unless we get another problem.

**Comment by TheDavidDelta** [comment]
Don't worry so much more about this. I'll learn about `buildx` and do it with it if it's viable. In addition, I may have to change to CircleCI in the future.

Very thanks for your help.

**Comment by TheFrenchGhosty** [comment]
@TheDavidDelta 

>I may have to change to CircleCI in the future.

I recommend Woodpecker CI, a fork of DroneCI before it went closed source.

**Pull request closed without merging**
